### ISSUE TITLE
Transfer Repo to Mapbox organization?

### ISSUE THREAD

**Issue by DenisCarriere** [mapbox/cross-street-indexer#7]
@morganherlocker @tcql do you want me to transfer this repo to Mapbox?

As long as this repo remains open source and I have commit access to it, I'm fine with doing the transfer.

The more heads the better.

**Comment by tcql** [comment]
@DenisCarriere yea that'd be perfect, if you don't mind

**Comment by DenisCarriere** [comment]
You might need to remove the fork for me to be able to transfer this repo. Or at least change the name of this forked repo.

**Comment by tcql** [comment]
@DenisCarriere renamed, see if that works. We'll need to also make sure I've got NPM publish access once it's moved?

**Comment by DenisCarriere** [comment]
Humm... still not working :( Any suggestions?

![image](https://user-images.githubusercontent.com/550895/27592991-ffbc39b6-5b23-11e7-9f7a-50030c664aae.png)

**Comment by tcql** [comment]
@DenisCarriere yea looks like i'll have to delete it first. I'll back up the issues and branches and delete, then you can transfer

**Comment by DenisCarriere** [comment]
Ok sounds good, note: i tried changing the name on my side and it's the same issue.

![image](https://user-images.githubusercontent.com/550895/27593307-d3a471c6-5b24-11e7-99a8-4713bc1bda6e.png)

Send me a ping whenever it's backed up.

**Comment by tcql** [comment]
@DenisCarriere okay, good on my end, i'm about to hit delete :)

**Comment by DenisCarriere** [comment]
👍

**Comment by tcql** [comment]
Sorry, technical difficulty delay. Deleting my end is still an option, but I thought of another. The other option is if you delete your repo, then this one would become the new "parent repo". I can add you as a collaborator. Then the current branch and ticket history is preserved

**Comment by DenisCarriere** [comment]
Oh that works... that might be a better option. OK we can try that

**Comment by DenisCarriere** [comment]
Perfect, that was a lot easier.. 👍 Just add me as a collaborator/admin

**Comment by DenisCarriere** [comment]
@tcql @morganherlocker Added you both as Collaborators to the NPM repo.

https://www.npmjs.com/package/cross-street-indexer/access

**Comment by morganherlocker** [comment]
Thanks Denis!

**Comment by DenisCarriere** [comment]
👍 Pretty excited to pass on the torch, I'll be following the issues, don't hesitate to `@` me.
